name: Deploy Recipe Sharing Application
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy-frontend.outputs.url }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.GOOGLECLOUD_SERVICE_ACCOUNT }}
          credentials_json: ${{ secrets.GOOGLECLOUD_CREDENTIALS }}
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/recipe-backend:latest
      - id: deploy-backend
        name: Deploy backend
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: recipe-backend
          image: ${{ secrets.DOCKERHUB_USERNAME }}/recipe-backend:latest
          region: ${{ secrets.GOOGLECLOUD_REGION }}
          flags: '--port=8080 --memory=1Gi --cpu=1 --timeout=300 --max-instances=10'
          env_vars: |
            PORT=8080
            DATABASE_URL=${{ secrets.MONGODB_CONNECTION_STRING }}
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/recipe-frontend:latest
          build-args: VITE_BACKEND_URL=${{ steps.deploy-backend.outputs.url }}/api/v1
      - id: deploy-frontend
        name: Deploy frontend
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: recipe-frontend
          image: ${{ secrets.DOCKERHUB_USERNAME }}/recipe-frontend:latest
          region: ${{ secrets.GOOGLECLOUD_REGION }}
